feat: add selic graph and investiment simulation
DataForgeFin/forge-app pull request #2
Opened 2023-07-23 23:22 UTC by andrelucassc

# Changes
- Adds connection to pymongo
- Adds selic graph in main page
- Adds selector for investiment simulation for Selic rates

# Todo
Adding a % diff to the SELIC rate since most of the rates will follow Selic but won't be the same.

2023-07-29 21:00 UTC, Arlenwass requested changes

2023-07-29 21:00 UTC, Arlenwass commented on data/selic.py
Sugiro mover esse arquivo para dentro de src. O diretório data é sobre dados, nao pacotes que interagem com dados.

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +    df = get_selic(datetime(year=2023, month=1, day=1))
Esse objeto não é um pd.dataframe, mas um pymongo.cursor. Esse nome de váriavel fica confuso pra mim por causa disso.

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +    fig = px.line(df, x="date", y="value")
Os argumentos `x` e `y` são válidos quando o primeiro argumento (`data_frame`) é do tipo pandas.DataFrame . Estou recebendo esse erro:

> ValueError: Value of 'x' is not the name of a column in 'data_frame'. Expected one of [] but received: date

2023-07-29 21:00 UTC, Arlenwass commented on data/selic.py
> +    query = {"date": {"$gte": start_date, "$lte": end_date}}
Filtrar os dados do tipo Selic, pois temos CDI na base também e teremos outros tipos no futuro.

2023-07-29 21:00 UTC, Arlenwass commented on data/selic.py
> +    return result
Sugiro fazer um parsing desse `result` para um lista de dicionários para não precisar transitar cursores mongo para o callback.

2023-07-29 21:00 UTC, Arlenwass commented on data/selic.py
> +    result = collection.find(query)
Sugiro trazer apenas os atributos que serão utilizados. 
```suggestion
    result = collection.find(query, {"date":1, "value":1, "_id": False})
```

2023-07-29 21:00 UTC, Arlenwass commented on data/selic.py
> +    db = client[settings.mongo_db]
Seria bom criar uma outra função para a instanciar o client mongo, provavelmente será utilizado em outras situações.

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +                {"label": "Tesouro Selic", "value": 2},
```suggestion
                {"label": "Prefixado", "value": "prefixado"},
                {"label": "Tesouro Selic", "value": "selic"},
```

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +    df = get_selic(datetime(year=2023, month=1, day=1))
Remover o hardcoded da Selic

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +        expected_selic = pd.DataFrame(get_selic(datetime.now() - relativedelta(months=1)))[
Precisamos converter para dataframe?

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +        expected_selic = pd.DataFrame(get_selic(datetime.now() - relativedelta(months=1)))[
Não deveríamos aplicar as taxas Selic de acordo com o período investido?

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +        monthly_rate = convert_yearly_to_monthly_rate(expected_selic / 100)
Precisamos descontar imposto de renda também.

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +        monthly_rate = convert_yearly_to_monthly_rate(expected_selic / 100)
IOF também entra na conta se o período for menor que 30 dias, mas podemos colocar um aviso no app falando sobre isso.

2023-07-29 21:00 UTC, Arlenwass commented on main.py
> +        dbc.RadioItems(
Melhorará a clareza do app se desabilitarmos o campo taxa_anual quando selecionado `Tesouro Selic`.

2023-07-31 23:17 UTC, andrelucassc commented on main.py
> +        expected_selic = pd.DataFrame(get_selic(datetime.now() - relativedelta(months=1)))[
Foi pego a última SELIC do período para prospectar o ganho futuro, considerando uma taxa fixa. Aceito sugestoes de como lidar com a previsao.

2023-07-31 23:18 UTC, andrelucassc commented on main.py
> +        monthly_rate = convert_yearly_to_monthly_rate(expected_selic / 100)
Criei as funcoes de impostos, mas acho que vale discutirmos esse ponto. Esses investimentos de prefixado e selic normalmente tem o imposto cobrado somente no final, daí seria aplicado somente no último valor. O que acha?

2023-08-01 21:51 UTC, Arlenwass approved these changes

2023-08-01 21:52 UTC, merged